class CEM2040 < ReportsPdf
  require 'prawn'

  # def initialize(report, view, options)
  #   super top_margin: 70
  #   @report = report
  #   @view = view
  #   build_report
  # end

  def build_report
    first_page
    second_page
    third_page
  end

  # Test method for rendering entire pdf with Prawn.
  def testem_page
    testem_fields(
      "#{Prawn::DATADIR}/images/reports/CEM2030-2012_Page_01.pdf"
      # "#{Rails.root}/app/assets/images/reports/testem_fields.pdf"
      # "#{Rails.root}/app/assets/pdfs/testem.png"
    )
    start_new_page
  end

  def first_page
    # page_background("#{Rails.root}/app/assets/pdfs/testem.png")
    # page_background("#{Prawn::DATADIR}/images/reports/CEM2030_production_v1.png")
    # page_background("#{Prawn::DATADIR}/images/reports/CEM2030-2012_Page_01.pdf")
    # full_report_header_block

    filename = "#{Prawn::DATADIR}/pdfs/cem/CEM2040_Page_1_small.png"
    pdf = Prawn::Document.new(
      background: filename
      # template: filename,
      # page_size: "A4"
    ) do
      # draw_text("stormsavvy", size: 12, at: [100,100])
      text("PDF generated by Storm Savvy", size: 12, align: :right)
      # image(filename, scale: 0.30)
    end
    pdf.render_file("#{Rails.root}/public/assets/cem2040_page_01.pdf")
    # send_data pdf.render, type: "application/pdf", disposition: "inline"

    start_new_page
  end

  def second_page
    # page_background("#{Prawn::DATADIR}/images/reports/CEM2030_production_v1.pdf")
    # page_background("#{Prawn::DATADIR}/images/reports/CEM2030-2012_Page_02.pdf")
    # simple_report_header_block

    filename = "#{Prawn::DATADIR}/pdfs/cem/CEM2040_Page_2_small.png"
    pdf = Prawn::Document.new(
      background: filename
    ) do
      text("PDF generated by Storm Savvy", size: 12, align: :right)
    end
    pdf.render_file("#{Rails.root}/public/assets/cem2040_page_02.pdf")
    start_new_page
  end

  def third_page
    # page_background("#{Prawn::DATADIR}/images/reports/CEM2030-2012_Page_03.pdf")
    # simple_report_header_block

    filename = "#{Prawn::DATADIR}/pdfs/cem/CEM2040_Page_3_small.png"
    pdf = Prawn::Document.new(
      background: filename
    ) do
      text("PDF generated by Storm Savvy", size: 12, align: :right)
    end
    pdf.render_file("#{Rails.root}/public/assets/cem2040_page_03.pdf")
    start_new_page
  end
end
