rails g migration RemoveFieldsFromReports\
    type:string\
    \
    site_information_name:string\
    site_address_1:string\
    site_address_2:string\
    site_city:string\
    site_state:string\
    site_zipcode:integer\
    contractor_name:string\
    contractor_address_1:string\
    contractor_address_2:string\
    contractor_city:string\
    contactor_state:string\
    contactor_zipcode:integer\
    contract_number:string\
    project_identifer_number:string\
    wdid_number:string\
    project_risk_level:integer\
    water_polution_control_manager_name:string\
    water_polution_control_manager_company_name:string\
    water_polution_control_manager_phone_number:string\
    water_polution_control_manager_emergancy_phone_number:string\
    inspector_name:string\
    date_of_inspection:date\
    weather_condition:string\
    precipitation_condition:string\
    wind_condition:string\
    construction_phase:string\
    site_information_acres_total_project_area:decimal\
    site_information_acres_total_project_disturbed_soil_area:decimal\
    site_information_acres_current_phase_disturbed_soil_area:decimal\
    \
    storm_information_time_elapsed_since_last_storm:string\
    storm_information_percipitation_since_last_storm:decimal\
    storm_information_time_storm_is_expected:datetime\
    storm_information_time_elapsed_since_storm_began:decimal\
    storm_information_time_elapsed_since_storm:decimal\
    storm_information_percipitation_amount_from_last_form:decimal\
    storm_information_expected_percipitaion_amount:decimal\
    \
    submitted_by_contractor:date\
    submitted_by_date:date\
    wpc_manager:string\
    wpc_phone:string\
    wpc_emergency_phone:string\
    inspection_date:date\
    total_area:decimal\
    total_DSA:decimal\
    current_DSA:decimal\
    inactive_DSA:decimal\
    time_elapsed_last_storm:decimal\
    precipitation_received:decimal\
    time_storm_expected:decimal\
    expected_precipitation_amount:decimal\
    time_elapsed_during_storm:decimal\
    gauge_reading_during_storm:decimal\
    time_elapsed_post_storm:decimal\
    gauge_reading_post_storm:decimal\
    contractor_state:string\
    contractor_zipcode:integer\
    water_polution_control_manager_emergency_phone_number:string\
    storm_information_expected_precipitaion_amount:decimal\
    water_pollution_control_manager_name:string\
    water_pollution_control_manager_company_name:string\
    water_pollution_control_manager_phone_number:string\
    water_pollution_control_manager_emergency_phone_number:string\
    storm_information_expected_precipitation_amount:decimal\
    storm_information_precipitation_amount_from_last_form:decimal\
    project_identifier_number:string
