rails g migration AddFieldsToSites\
  project_ea:string\
  wdid_number:string\
  construction_phase:string\
  \
  contractor_name:string\
  contractor_address_1:string\
  contractor_address_2:string\
  contractor_city:string\
  contractor_state:string\
  contractor_zipcode:string\
  contract_number:string\
  \
  wpcm_name:string\
  wpcm_company:string\
  wpcm_phone:string\
  wpcm_emergency_phone:string\
  qsp_name:string\
  qsp_company:string\
  qsp_phone:string\
  qsp_emergency_phone:string\
  \
  total_area:decimal\
  total_dsa:decimal\
  current_dsa:decimal\
  inactive_dsa:decimal\
  \
  time_since_last_storm:string\
  precipitation_received:decimal\
  \
  permits:string\
  resident_engineer_name:string\
  structures_representative_name:string\
  last_bmp_status:date\
  last_inspection:date\
  last_corrective_action:date\
  last_reap:date\
  last_training:date\
  last_weather_forecast:date\
  last_sampling:date\
