require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SamplingEventsController do

  # This should return the minimal set of attributes required to create a valid
  # SamplingEvent. As you add validations to SamplingEvent, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "site_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SamplingEventsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all sampling_events as @sampling_events" do
      sampling_event = SamplingEvent.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sampling_events).should eq([sampling_event])
    end
  end

  describe "GET show" do
    it "assigns the requested sampling_event as @sampling_event" do
      sampling_event = SamplingEvent.create! valid_attributes
      get :show, {:id => sampling_event.to_param}, valid_session
      assigns(:sampling_event).should eq(sampling_event)
    end
  end

  describe "GET new" do
    it "assigns a new sampling_event as @sampling_event" do
      get :new, {}, valid_session
      assigns(:sampling_event).should be_a_new(SamplingEvent)
    end
  end

  describe "GET edit" do
    it "assigns the requested sampling_event as @sampling_event" do
      sampling_event = SamplingEvent.create! valid_attributes
      get :edit, {:id => sampling_event.to_param}, valid_session
      assigns(:sampling_event).should eq(sampling_event)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SamplingEvent" do
        expect {
          post :create, {:sampling_event => valid_attributes}, valid_session
        }.to change(SamplingEvent, :count).by(1)
      end

      it "assigns a newly created sampling_event as @sampling_event" do
        post :create, {:sampling_event => valid_attributes}, valid_session
        assigns(:sampling_event).should be_a(SamplingEvent)
        assigns(:sampling_event).should be_persisted
      end

      it "redirects to the created sampling_event" do
        post :create, {:sampling_event => valid_attributes}, valid_session
        response.should redirect_to(SamplingEvent.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sampling_event as @sampling_event" do
        # Trigger the behavior that occurs when invalid params are submitted
        SamplingEvent.any_instance.stub(:save).and_return(false)
        post :create, {:sampling_event => { "site_id" => "invalid value" }}, valid_session
        assigns(:sampling_event).should be_a_new(SamplingEvent)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SamplingEvent.any_instance.stub(:save).and_return(false)
        post :create, {:sampling_event => { "site_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sampling_event" do
        sampling_event = SamplingEvent.create! valid_attributes
        # Assuming there are no other sampling_events in the database, this
        # specifies that the SamplingEvent created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SamplingEvent.any_instance.should_receive(:update_attributes).with({ "site_id" => "1" })
        put :update, {:id => sampling_event.to_param, :sampling_event => { "site_id" => "1" }}, valid_session
      end

      it "assigns the requested sampling_event as @sampling_event" do
        sampling_event = SamplingEvent.create! valid_attributes
        put :update, {:id => sampling_event.to_param, :sampling_event => valid_attributes}, valid_session
        assigns(:sampling_event).should eq(sampling_event)
      end

      it "redirects to the sampling_event" do
        sampling_event = SamplingEvent.create! valid_attributes
        put :update, {:id => sampling_event.to_param, :sampling_event => valid_attributes}, valid_session
        response.should redirect_to(sampling_event)
      end
    end

    describe "with invalid params" do
      it "assigns the sampling_event as @sampling_event" do
        sampling_event = SamplingEvent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SamplingEvent.any_instance.stub(:save).and_return(false)
        put :update, {:id => sampling_event.to_param, :sampling_event => { "site_id" => "invalid value" }}, valid_session
        assigns(:sampling_event).should eq(sampling_event)
      end

      it "re-renders the 'edit' template" do
        sampling_event = SamplingEvent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SamplingEvent.any_instance.stub(:save).and_return(false)
        put :update, {:id => sampling_event.to_param, :sampling_event => { "site_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sampling_event" do
      sampling_event = SamplingEvent.create! valid_attributes
      expect {
        delete :destroy, {:id => sampling_event.to_param}, valid_session
      }.to change(SamplingEvent, :count).by(-1)
    end

    it "redirects to the sampling_events list" do
      sampling_event = SamplingEvent.create! valid_attributes
      delete :destroy, {:id => sampling_event.to_param}, valid_session
      response.should redirect_to(sampling_events_url)
    end
  end

end
